server:
  port:8080

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    username: root
    password: okto2679!@#
    url: jdbc:mysql://localhost:3306/untitledProject?&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
    driver: com.mysql.cj.jdbc.Driver
# MyBatis ??
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    mapper-locations: classpath:/mapper/*.xml


#????

logging:
  level:
    root: INFO
    org:
      mybatis: DEBUG